### ISSUE TITLE
Add dependabot

### ISSUE THREAD

**Issue by jarrodldavis** [jarrodldavis/dotfiles#13]
`.github/dependabot.yml`

```yaml
version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
```
